# Generated by Django 6.0.4 on 2026-04-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=265)),
                ('explanation', models.TextField()),
                ('url', models.URLField()),
                ('media_type', models.CharField()),
                ('date', models.DateField()),
            ],
        ),
    ]
