# Generated by Django 6.0.4 on 2026-04-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apod',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
