# Generated by Django 6.0.4 on 2026-04-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apod', '0002_apod_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='apod',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
